export const config = {
  CONTENTFUL_SPACE_ID: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
  CONTENTUL_ACCESS_TOKEN: process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN,
  NEXT_PUBLIC_HOME_PAGE_ENTRY_ID:
    process.env.NEXT_PUBLIC_HOME_PAGE_ENTRY_ID || "",
  NEXT_PUBLIC_BLOG_PAGE_ENTRY_ID:
    process.env.NEXT_PUBLIC_BLOG_PAGE_ENTRY_ID || "",
}
